import type { CanvasEdgeSeed, CanvasNodeSeed } from "@/lib/workflow-canvas/types";

/**
 * Canonical Saurabh Arora workflow canvas seed. Used by:
 *   * supabase/migrations/0021_seed_saurabh_arora.sql (compiled to SQL)
 *   * runtime template lookup when "Refined Oil C&F" template is chosen
 *
 * Layout strategy (Phase A — basic): three horizontal bands, one per phase.
 * Each phase lays nodes out roughly by stage (purchase → sales → dispatch
 * → billing → freight → dashboard). Phase B will replace this with proper
 * swimlanes.
 */

// Layout helpers — keep math compact.
const COL = (stage: number): number => 80 + stage * 280; // stage column X
const ROW_CURRENT = 80;
const ROW_PROPOSED = 1100;
const ROW_AI = 2100;

// =========================================================================
// CURRENT MANUAL WORKFLOW
// =========================================================================

export const CURRENT_NODES: CanvasNodeSeed[] = [
  {
    node_key: "current.purchase.deal_booking",
    node_type: "process",
    phase: "current_manual",
    department: "management",
    visibility: "shared_all",
    title: "Purchase Deal Booking",
    short_label: "Purchase Deal",
    actors: ["MD / Management", "Supplier / Company"],
    current_process:
      "MD negotiates rates with supplier/company and confirms the purchase deal with terms and conditions, currently shared through WhatsApp.",
    pain_points: [
      "Deal terms scattered in WhatsApp",
      "Weak approval trail",
      "Rate, quantity, discount, and terms can be misread",
    ],
    documents: ["Deal confirmation", "Terms note"],
    risk_level: "high",
    automation_potential: "high",
    position_x: COL(0),
    position_y: ROW_CURRENT,
  },
  {
    node_key: "current.purchase.sheet_entry",
    node_type: "process",
    phase: "current_manual",
    department: "accounts",
    visibility: "shared_all",
    title: "Purchase Sheet Entry",
    actors: ["Accounts"],
    current_process:
      "Accounts creates purchase deal sheet and enters it into existing software.",
    pain_points: [
      "Duplicate entry",
      "Manual dependency",
      "Possibility of incorrect data entry",
    ],
    risk_level: "medium",
    automation_potential: "high",
    position_x: COL(0),
    position_y: ROW_CURRENT + 140,
  },
  {
    node_key: "current.purchase.recheck",
    node_type: "approval",
    phase: "current_manual",
    department: "accounts",
    visibility: "shared_all",
    title: "Second-Level Recheck",
    actors: ["Accounts"],
    current_process:
      "A second person rechecks details from WhatsApp, sheet, and software.",
    pain_points: [
      "Time-consuming manual verification",
      "Data exists in multiple places",
      "No single source of truth",
    ],
    risk_level: "medium",
    automation_potential: "high",
    position_x: COL(0),
    position_y: ROW_CURRENT + 280,
  },
  {
    node_key: "current.purchase.dispatch_request",
    node_type: "process",
    phase: "current_manual",
    department: "commercial",
    visibility: "shared_all",
    title: "Dispatch Request to Supplier",
    actors: ["Commercial Assistant", "MD", "Sales Team"],
    current_process:
      "Commercial assistant discusses stock requirement with sales team, gets MD approval, and sends dispatch request to supplier/company for plant/rake/CFA dispatch to own godown or direct party godown on bill-to-ship-to basis.",
    pain_points: [
      "Manual coordination",
      "Approval delays",
      "Bill-to-ship-to tracking complexity",
    ],
    risk_level: "high",
    automation_potential: "medium",
    position_x: COL(0),
    position_y: ROW_CURRENT + 420,
  },
  {
    node_key: "current.purchase.supplier_invoice",
    node_type: "document",
    phase: "current_manual",
    department: "accounts",
    visibility: "shared_all",
    title: "Supplier Invoice Email",
    actors: ["Accounts", "Supplier"],
    current_process:
      "When stocks are billed and dispatched, the company sends an email. Accounts enters the invoice in software under Stock in Transit.",
    pain_points: ["Manual invoice entry", "Delayed stock visibility"],
    documents: ["Supplier Invoice"],
    risk_level: "medium",
    automation_potential: "high",
    position_x: COL(0),
    position_y: ROW_CURRENT + 560,
  },
  {
    node_key: "current.purchase.invoice_recon",
    node_type: "process",
    phase: "current_manual",
    department: "accounts",
    visibility: "shared_all",
    title: "Purchase Invoice Reconciliation",
    actors: ["Accountant"],
    current_process:
      "Accountant checks invoice against booked rate, discounts, schemes, plant discount, rake discount, offers, and other terms.",
    pain_points: [
      "Manual checking effort",
      "Missed discounts",
      "Delayed difference report",
    ],
    risk_level: "high",
    automation_potential: "high",
    position_x: COL(0),
    position_y: ROW_CURRENT + 700,
  },
  {
    node_key: "current.purchase.truck_arrival",
    node_type: "process",
    phase: "current_manual",
    department: "depot_godown",
    visibility: "shared_all",
    title: "Truck Arrival Report",
    actors: ["Depot / Godown Team"],
    current_process:
      "Depot shares truck arrival details with head office through WhatsApp.",
    pain_points: ["WhatsApp dependency", "Delayed visibility"],
    risk_level: "medium",
    automation_potential: "high",
    position_x: COL(1),
    position_y: ROW_CURRENT,
  },
  {
    node_key: "current.purchase.goods_arrival",
    node_type: "document",
    phase: "current_manual",
    department: "depot_godown",
    visibility: "shared_all",
    title: "Goods Arrival Report",
    actors: ["Godown Team"],
    current_process:
      "After unloading, godown team records quantity, fresh stock, damaged stock, leakage, wet/dented stock, oil loss, WMS/location, and prepares signed Goods Arrival Report.",
    pain_points: [
      "Physical document dependency",
      "Condition-wise stock update delayed",
      "Damage/leakage claim delay risk",
    ],
    documents: ["Goods Arrival Report"],
    risk_level: "high",
    automation_potential: "high",
    position_x: COL(1),
    position_y: ROW_CURRENT + 140,
  },
  {
    node_key: "current.purchase.move_to_available",
    node_type: "process",
    phase: "current_manual",
    department: "head_office",
    visibility: "shared_all",
    title: "Move Stock — In Transit → Available",
    actors: ["Head Office"],
    current_process:
      "Goods Arrival Report is shared with head office after finalization so stock can move from Stock in Transit to available stock.",
    pain_points: [
      "Sales team may not have live saleable stock visibility",
      "In-transit and saleable stock can be confused",
    ],
    risk_level: "medium",
    automation_potential: "high",
    position_x: COL(1),
    position_y: ROW_CURRENT + 280,
  },
  {
    node_key: "current.sales.daily_rate",
    node_type: "process",
    phase: "current_manual",
    department: "management",
    visibility: "shared_all",
    title: "Daily Selling Rate",
    actors: ["MD", "Sales Heads", "Sales Team"],
    current_process:
      "MD discusses market trend with sales heads and sales team and gives daily selling rates.",
    pain_points: ["Informal rate communication", "No version control"],
    risk_level: "medium",
    automation_potential: "medium",
    position_x: COL(2),
    position_y: ROW_CURRENT,
  },
  {
    node_key: "current.sales.deal_booking",
    node_type: "process",
    phase: "current_manual",
    department: "sales",
    visibility: "shared_all",
    title: "Sales Deal Booking",
    actors: ["Sales Team", "Broker", "Party"],
    current_process:
      "Price list is shared with brokers and parties. Offers are received through WhatsApp groups and confirmed or rejected by MD.",
    pain_points: [
      "Offers scattered in WhatsApp",
      "Rate/quantity disputes possible",
      "Manual confirmation tracking",
    ],
    risk_level: "high",
    automation_potential: "high",
    position_x: COL(2),
    position_y: ROW_CURRENT + 140,
  },
  {
    node_key: "current.sales.sheet_entry",
    node_type: "process",
    phase: "current_manual",
    department: "commercial",
    visibility: "shared_all",
    title: "Sales Sheet Entry",
    actors: ["Commercial Assistant"],
    current_process:
      "Commercial assistant creates sales deal sheet and enters it in software.",
    pain_points: ["Duplicate entry", "Mismatch risk"],
    risk_level: "medium",
    automation_potential: "high",
    position_x: COL(2),
    position_y: ROW_CURRENT + 280,
  },
  {
    node_key: "current.sales.recheck",
    node_type: "approval",
    phase: "current_manual",
    department: "accounts",
    visibility: "shared_all",
    title: "Sales Entry Recheck",
    actors: ["Accounts", "Commercial"],
    current_process:
      "Second person rechecks from WhatsApp, sheet, and software.",
    pain_points: [
      "Manual verification burden",
      "No single source of truth",
    ],
    risk_level: "medium",
    automation_potential: "high",
    position_x: COL(2),
    position_y: ROW_CURRENT + 420,
  },
  {
    node_key: "current.sales.dispatch_req",
    node_type: "process",
    phase: "current_manual",
    department: "commercial",
    visibility: "shared_all",
    title: "Dispatch Requirement Received",
    actors: ["Commercial Assistant", "Brokers", "Parties", "Sales Team"],
    current_process:
      "Commercial assistant receives loading/dispatch requirement from brokers, parties, or sales team.",
    pain_points: [
      "Dispatch requests come from multiple sources",
      "No structured allocation",
    ],
    risk_level: "medium",
    automation_potential: "high",
    position_x: COL(3),
    position_y: ROW_CURRENT,
  },
  {
    node_key: "current.sales.credit_check",
    node_type: "decision",
    phase: "current_manual",
    department: "commercial",
    visibility: "shared_all",
    title: "Credit Limit & Overdue Check",
    actors: ["Commercial Assistant", "Accounts", "Sales Head"],
    current_process:
      "Commercial assistant checks party limit, overdue, blocked status, and discusses dispatch with sales head.",
    pain_points: [
      "Manual credit check",
      "Risky dispatch if overdue not identified",
      "Approval delay",
    ],
    risk_level: "high",
    automation_potential: "high",
    position_x: COL(3),
    position_y: ROW_CURRENT + 140,
  },
  {
    node_key: "current.sales.blocked_approval",
    node_type: "approval",
    phase: "current_manual",
    department: "management",
    visibility: "shared_all",
    title: "Blocked Party / Adhoc Approval",
    actors: ["Management", "Accounts"],
    current_process:
      "If required, approval for blocked party or adhoc credit is initiated through WhatsApp.",
    pain_points: [
      "Informal approval trail",
      "Delay in opening party",
    ],
    risk_level: "high",
    automation_potential: "medium",
    position_x: COL(3),
    position_y: ROW_CURRENT + 280,
  },
  {
    node_key: "current.dispatch.excel_program",
    node_type: "document",
    phase: "current_manual",
    department: "commercial",
    visibility: "shared_all",
    title: "Excel Dispatch Program",
    actors: ["Commercial Assistant", "Depot"],
    current_process:
      "If party is cleared, dispatch program is sent to depot on Excel via WhatsApp.",
    pain_points: [
      "Excel dependency",
      "Depot may not have latest changes",
    ],
    documents: ["Dispatch Program (Excel)"],
    risk_level: "medium",
    automation_potential: "high",
    position_x: COL(3),
    position_y: ROW_CURRENT + 420,
  },
  {
    node_key: "current.dispatch.delivery_order",
    node_type: "document",
    phase: "current_manual",
    department: "depot_godown",
    visibility: "shared_all",
    title: "Delivery Order",
    actors: ["Depot", "Driver / Transporter"],
    current_process:
      "Depot arranges vehicle or party sends vehicle. Delivery Order is created and handed to driver.",
    pain_points: [
      "Paper-based process",
      "Vehicle and driver data not linked properly",
    ],
    documents: ["Delivery Order"],
    risk_level: "medium",
    automation_potential: "high",
    position_x: COL(4),
    position_y: ROW_CURRENT,
  },
  {
    node_key: "current.dispatch.loading",
    node_type: "process",
    phase: "current_manual",
    department: "depot_godown",
    visibility: "shared_all",
    title: "Loading at Godown",
    actors: ["Godown Incharge"],
    current_process:
      "Godown incharge loads vehicle, enters details in physical register, signs DO, and sends it back to office for billing.",
    pain_points: [
      "Physical register dependency",
      "Delayed billing trigger",
      "Loading mismatch risk",
    ],
    risk_level: "high",
    automation_potential: "high",
    position_x: COL(4),
    position_y: ROW_CURRENT + 140,
  },
  {
    node_key: "current.billing.invoice",
    node_type: "process",
    phase: "current_manual",
    department: "accounts",
    visibility: "shared_all",
    title: "Billing",
    actors: ["Depot Accountant", "Accounts"],
    current_process:
      "Depot accountant checks DO against loading program and initiates invoice. Bill-to-ship-to cases require same-day billing from BTST godown.",
    pain_points: [
      "Manual document matching",
      "Billing delay",
      "Bill-to-ship-to tracking complexity",
    ],
    documents: ["Sales Invoice"],
    risk_level: "high",
    automation_potential: "high",
    position_x: COL(5),
    position_y: ROW_CURRENT,
  },
  {
    node_key: "current.billing.doc_recheck",
    node_type: "document",
    phase: "current_manual",
    department: "accounts",
    visibility: "shared_all",
    title: "Document Recheck & Vehicle Release",
    actors: ["Office", "Accounts Assistant"],
    current_process:
      "Invoices and documents are rechecked manually and handed to driver before vehicle leaves.",
    pain_points: [
      "Missing document risk",
      "Delayed vehicle release",
    ],
    risk_level: "medium",
    automation_potential: "high",
    position_x: COL(5),
    position_y: ROW_CURRENT + 140,
  },
  {
    node_key: "current.billing.pod",
    node_type: "document",
    phase: "current_manual",
    department: "head_office",
    visibility: "shared_all",
    title: "Delivery Receiving / POD",
    actors: ["Depot Office", "Head Office"],
    current_process:
      "After delivery, depot office checks receiving and records delivery. Issues are escalated to head office.",
    pain_points: [
      "POD tracking is manual",
      "Issue escalation delayed",
    ],
    documents: ["POD", "Receiving Copy"],
    risk_level: "medium",
    automation_potential: "high",
    position_x: COL(5),
    position_y: ROW_CURRENT + 280,
  },
  {
    node_key: "current.freight.entry",
    node_type: "process",
    phase: "current_manual",
    department: "accounts",
    visibility: "shared_all",
    title: "Freight Entry",
    actors: ["Depot Accountant"],
    current_process: "Depot accountant enters daily freight entries.",
    pain_points: [
      "Freight not always linked to transaction, vehicle, route, and invoice",
    ],
    risk_level: "medium",
    automation_potential: "high",
    position_x: COL(6),
    position_y: ROW_CURRENT,
  },
  {
    node_key: "current.freight.cash_closing",
    node_type: "process",
    phase: "current_manual",
    department: "accounts",
    visibility: "shared_all",
    title: "Cash Closing",
    actors: ["Office", "Accounts Assistant"],
    current_process:
      "Daily cash records are updated, printed, signed, and sent through WhatsApp to head office.",
    pain_points: [
      "Manual closing",
      "WhatsApp reporting",
      "Delayed reconciliation",
    ],
    risk_level: "high",
    automation_potential: "high",
    position_x: COL(6),
    position_y: ROW_CURRENT + 140,
  },
  {
    node_key: "current.freight.head_office_recon",
    node_type: "process",
    phase: "current_manual",
    department: "head_office",
    visibility: "shared_all",
    title: "Head Office Reconciliation",
    actors: ["Head Office", "Sales / Commercial"],
    current_process:
      "Head office gets BTST documents and receiving from parties through sales/commercial team help.",
    pain_points: [
      "Follow-up dependency",
      "Missing documents",
      "Delayed closure",
    ],
    risk_level: "medium",
    automation_potential: "high",
    position_x: COL(6),
    position_y: ROW_CURRENT + 280,
  },
];

export const CURRENT_EDGES: CanvasEdgeSeed[] = [
  // Purchase chain
  ["current.purchase.deal_booking", "current.purchase.sheet_entry"],
  ["current.purchase.sheet_entry", "current.purchase.recheck"],
  ["current.purchase.recheck", "current.purchase.dispatch_request"],
  ["current.purchase.dispatch_request", "current.purchase.supplier_invoice"],
  ["current.purchase.supplier_invoice", "current.purchase.invoice_recon"],
  ["current.purchase.invoice_recon", "current.purchase.truck_arrival"],
  ["current.purchase.truck_arrival", "current.purchase.goods_arrival"],
  ["current.purchase.goods_arrival", "current.purchase.move_to_available"],
  // Sales chain
  ["current.sales.daily_rate", "current.sales.deal_booking"],
  ["current.sales.deal_booking", "current.sales.sheet_entry"],
  ["current.sales.sheet_entry", "current.sales.recheck"],
  ["current.sales.recheck", "current.sales.dispatch_req"],
  ["current.sales.dispatch_req", "current.sales.credit_check"],
  // Conditional branches from credit check
  ["current.sales.credit_check", "current.sales.blocked_approval"],
  ["current.sales.credit_check", "current.dispatch.excel_program"],
  ["current.sales.blocked_approval", "current.dispatch.excel_program"],
  // Dispatch & billing chain
  ["current.dispatch.excel_program", "current.dispatch.delivery_order"],
  ["current.dispatch.delivery_order", "current.dispatch.loading"],
  ["current.dispatch.loading", "current.billing.invoice"],
  ["current.billing.invoice", "current.billing.doc_recheck"],
  ["current.billing.doc_recheck", "current.billing.pod"],
  ["current.billing.pod", "current.freight.entry"],
  ["current.freight.entry", "current.freight.cash_closing"],
  ["current.freight.cash_closing", "current.freight.head_office_recon"],
].map(([s, t], i) => ({
  edge_key: `current.e${i + 1}`,
  source_node_key: s,
  target_node_key: t,
  edge_type: "normal",
  phase: "current_manual" as const,
  visibility: "shared_all" as const,
}));

// =========================================================================
// PROPOSED ERP WORKFLOW
// =========================================================================

export const ERP_NODES: CanvasNodeSeed[] = [
  {
    node_key: "erp.purchase.deal_booking",
    node_type: "process",
    phase: "proposed_erp",
    department: "system",
    visibility: "shared_all",
    title: "Purchase Deal Booking",
    proposed_process:
      "Create Purchase Deal Booking with supplier, product, quantity, booked rate, terms, discount, scheme, delivery point, validity, and approval status.",
    erp_modules: ["Purchase Management"],
    data_captured: [
      "Supplier", "Product", "Quantity", "Booked Rate",
      "Terms", "Discount", "Scheme", "Delivery Point", "Validity",
    ],
    automation_potential: "high",
    position_x: COL(0),
    position_y: ROW_PROPOSED,
  },
  {
    node_key: "erp.purchase.approval_trail",
    node_type: "approval",
    phase: "proposed_erp",
    department: "system",
    visibility: "shared_all",
    title: "Approval Trail",
    proposed_process:
      "All deal approvals are recorded with user, timestamp, comments, and version history.",
    erp_modules: ["Purchase Management", "Approval Workflow"],
    data_captured: ["User", "Timestamp", "Comments", "Version"],
    automation_potential: "high",
    position_x: COL(0),
    position_y: ROW_PROPOSED + 140,
  },
  {
    node_key: "erp.purchase.invoice_import",
    node_type: "system",
    phase: "proposed_erp",
    department: "system",
    visibility: "shared_all",
    title: "Purchase Invoice Import",
    proposed_process:
      "Supplier invoice creates Stock in Transit and links to Purchase Deal.",
    erp_modules: ["Purchase Management", "Inventory"],
    automation_potential: "high",
    position_x: COL(0),
    position_y: ROW_PROPOSED + 280,
  },
  {
    node_key: "erp.purchase.invoice_recon",
    node_type: "system",
    phase: "proposed_erp",
    department: "system",
    visibility: "shared_all",
    title: "Invoice Reconciliation",
    proposed_process:
      "System compares invoice against booked rate, quantity, discounts, schemes, and terms.",
    erp_modules: ["Purchase Management"],
    automation_potential: "high",
    position_x: COL(0),
    position_y: ROW_PROPOSED + 420,
  },
  {
    node_key: "erp.inventory.goods_arrival",
    node_type: "document",
    phase: "proposed_erp",
    department: "depot_godown",
    visibility: "shared_all",
    title: "Goods Arrival Report",
    proposed_process:
      "Mobile Goods Arrival Report captures received quantity, condition-wise stock, batch, godown, WMS/location, and driver confirmation.",
    erp_modules: ["Inventory", "Mobile App"],
    documents: ["Goods Arrival Report"],
    data_captured: [
      "Received Quantity", "Condition-wise Stock", "Batch",
      "Godown", "WMS Location", "Driver Confirmation",
    ],
    automation_potential: "high",
    position_x: COL(1),
    position_y: ROW_PROPOSED,
  },
  {
    node_key: "erp.inventory.condition_wise",
    node_type: "data",
    phase: "proposed_erp",
    department: "system",
    visibility: "shared_all",
    title: "Condition-wise Inventory",
    proposed_process:
      "Stock moves automatically into Available, Damaged, Wet/Dented, Leakage, or Loose locations.",
    erp_modules: ["Inventory", "Godown Management"],
    data_captured: ["Available", "Damaged", "Wet/Dented", "Leakage", "Loose"],
    automation_potential: "high",
    position_x: COL(1),
    position_y: ROW_PROPOSED + 140,
  },
  {
    node_key: "erp.sales.deal_booking",
    node_type: "process",
    phase: "proposed_erp",
    department: "sales",
    visibility: "shared_all",
    title: "Sales Deal Booking",
    proposed_process:
      "Sales Deal Booking captures party, broker, product, rate, quantity, discount, terms, validity, and approval.",
    erp_modules: ["Sales", "Deal Booking Management"],
    data_captured: [
      "Party", "Broker", "Product", "Rate", "Quantity",
      "Discount", "Terms", "Validity", "Approval",
    ],
    automation_potential: "high",
    position_x: COL(2),
    position_y: ROW_PROPOSED,
  },
  {
    node_key: "erp.sales.credit_check",
    node_type: "decision",
    phase: "proposed_erp",
    department: "system",
    visibility: "shared_all",
    title: "Automated Credit Check",
    proposed_process:
      "ERP checks credit limit, overdue, blocked status, due days, deal limit, and adhoc approval requirement.",
    erp_modules: ["Credit Control", "Sales"],
    data_captured: [
      "Credit Limit", "Overdue", "Blocked Status",
      "Due Days", "Deal Limit", "Adhoc Approval",
    ],
    automation_potential: "high",
    position_x: COL(3),
    position_y: ROW_PROPOSED,
  },
  {
    node_key: "erp.dispatch.program",
    node_type: "system",
    phase: "proposed_erp",
    department: "system",
    visibility: "shared_all",
    title: "Dispatch Program",
    proposed_process:
      "System generates dispatch program linked to approved Sales Deal and available stock.",
    erp_modules: ["Dispatch", "Sales", "Inventory"],
    automation_potential: "high",
    position_x: COL(3),
    position_y: ROW_PROPOSED + 140,
  },
  {
    node_key: "erp.dispatch.delivery_order",
    node_type: "document",
    phase: "proposed_erp",
    department: "depot_godown",
    visibility: "shared_all",
    title: "Delivery Order",
    proposed_process:
      "Delivery Order is generated with vehicle, driver, transporter, product, batch, quantity, and destination.",
    erp_modules: ["Dispatch", "Documents"],
    documents: ["Delivery Order"],
    data_captured: [
      "Vehicle", "Driver", "Transporter", "Product",
      "Batch", "Quantity", "Destination",
    ],
    automation_potential: "high",
    position_x: COL(4),
    position_y: ROW_PROPOSED,
  },
  {
    node_key: "erp.dispatch.loading_confirm",
    node_type: "process",
    phase: "proposed_erp",
    department: "depot_godown",
    visibility: "shared_all",
    title: "Mobile Loading Confirmation",
    proposed_process:
      "Godown confirms loading through mobile with batch, quantity, condition, vehicle, timestamp, and user confirmation.",
    erp_modules: ["Dispatch", "Mobile App"],
    automation_potential: "high",
    position_x: COL(4),
    position_y: ROW_PROPOSED + 140,
  },
  {
    node_key: "erp.billing.invoice_trigger",
    node_type: "system",
    phase: "proposed_erp",
    department: "system",
    visibility: "shared_all",
    title: "Invoice Trigger",
    proposed_process:
      "Invoice is triggered after loading confirmation. Bill-to-ship-to rules are supported.",
    erp_modules: ["Billing", "Sales"],
    automation_potential: "high",
    position_x: COL(5),
    position_y: ROW_PROPOSED,
  },
  {
    node_key: "erp.billing.doc_checklist",
    node_type: "document",
    phase: "proposed_erp",
    department: "system",
    visibility: "shared_all",
    title: "Document Checklist",
    proposed_process:
      "System checks required invoice, DO, e-way bill, POD, and receiving documents.",
    erp_modules: ["Documents", "Billing"],
    documents: ["Invoice", "DO", "E-way Bill", "POD", "Receiving"],
    automation_potential: "high",
    position_x: COL(5),
    position_y: ROW_PROPOSED + 140,
  },
  {
    node_key: "erp.billing.pod_upload",
    node_type: "document",
    phase: "proposed_erp",
    department: "depot_godown",
    visibility: "shared_all",
    title: "POD & Receiving Upload",
    proposed_process:
      "POD and receiving copy are uploaded and linked to invoice/order.",
    erp_modules: ["Documents", "Mobile App"],
    documents: ["POD", "Receiving Copy"],
    automation_potential: "high",
    position_x: COL(5),
    position_y: ROW_PROPOSED + 280,
  },
  {
    node_key: "erp.freight.management",
    node_type: "process",
    phase: "proposed_erp",
    department: "accounts",
    visibility: "shared_all",
    title: "Freight Management",
    proposed_process:
      "Freight is linked to vehicle, transporter, route, invoice, party, and dispatch.",
    erp_modules: ["Freight"],
    automation_potential: "high",
    position_x: COL(6),
    position_y: ROW_PROPOSED,
  },
  {
    node_key: "erp.freight.cash_closing",
    node_type: "process",
    phase: "proposed_erp",
    department: "accounts",
    visibility: "shared_all",
    title: "Digital Cash Closing",
    proposed_process:
      "Cash closing is entered, approved, and visible to head office digitally.",
    erp_modules: ["Cash Management", "Accounts"],
    automation_potential: "high",
    position_x: COL(6),
    position_y: ROW_PROPOSED + 140,
  },
  {
    node_key: "erp.dashboard.management",
    node_type: "system",
    phase: "proposed_erp",
    department: "management",
    visibility: "shared_all",
    title: "Management Dashboard",
    proposed_process:
      "Dashboard shows exceptions, pending approvals, in-transit stock, pending billing, POD pending, freight pending, cash closing pending, and margin leakage.",
    erp_modules: ["Dashboard", "Decision Intelligence"],
    automation_potential: "high",
    position_x: COL(6),
    position_y: ROW_PROPOSED + 280,
  },
];

export const ERP_EDGES: CanvasEdgeSeed[] = [
  ["erp.purchase.deal_booking", "erp.purchase.approval_trail"],
  ["erp.purchase.approval_trail", "erp.purchase.invoice_import"],
  ["erp.purchase.invoice_import", "erp.purchase.invoice_recon"],
  ["erp.purchase.invoice_recon", "erp.inventory.goods_arrival"],
  ["erp.inventory.goods_arrival", "erp.inventory.condition_wise"],
  ["erp.inventory.condition_wise", "erp.sales.deal_booking"],
  ["erp.sales.deal_booking", "erp.sales.credit_check"],
  ["erp.sales.credit_check", "erp.dispatch.program"],
  ["erp.dispatch.program", "erp.dispatch.delivery_order"],
  ["erp.dispatch.delivery_order", "erp.dispatch.loading_confirm"],
  ["erp.dispatch.loading_confirm", "erp.billing.invoice_trigger"],
  ["erp.billing.invoice_trigger", "erp.billing.doc_checklist"],
  ["erp.billing.doc_checklist", "erp.billing.pod_upload"],
  ["erp.billing.pod_upload", "erp.freight.management"],
  ["erp.freight.management", "erp.freight.cash_closing"],
  ["erp.freight.cash_closing", "erp.dashboard.management"],
].map(([s, t], i) => ({
  edge_key: `erp.e${i + 1}`,
  source_node_key: s,
  target_node_key: t,
  edge_type: "system_automation",
  phase: "proposed_erp" as const,
  visibility: "shared_all" as const,
}));

// =========================================================================
// ERP + AI WORKFLOW
// =========================================================================

export const AI_NODES: CanvasNodeSeed[] = [
  {
    node_key: "ai.whatsapp_extraction",
    node_type: "ai",
    phase: "erp_ai",
    department: "ai_layer",
    visibility: "shared_all",
    title: "WhatsApp-to-ERP Extraction",
    description:
      "Extract Purchase Deal, Sales Deal, approvals, dispatch requests, and rate confirmations from WhatsApp-style messages or uploaded screenshots.",
    ai_opportunity:
      "Eliminates the WhatsApp dependency that creates the largest single source of operational friction.",
    erp_modules: ["AI Layer", "Purchase", "Sales"],
    automation_potential: "high",
    position_x: COL(0),
    position_y: ROW_AI,
  },
  {
    node_key: "ai.invoice_matching",
    node_type: "ai",
    phase: "erp_ai",
    department: "ai_layer",
    visibility: "shared_all",
    title: "Invoice Matching Assistant",
    description:
      "Compare supplier invoice with Purchase Deal terms, discounts, schemes, plant discount, rake discount, offers, quantity, and rate.",
    ai_opportunity:
      "Catches missed discounts and plant/rake scheme leakage automatically.",
    erp_modules: ["AI Layer", "Purchase Management"],
    automation_potential: "high",
    position_x: COL(0),
    position_y: ROW_AI + 140,
  },
  {
    node_key: "ai.credit_risk_alert",
    node_type: "ai",
    phase: "erp_ai",
    department: "ai_layer",
    visibility: "shared_all",
    title: "Credit Risk Alert",
    description:
      "Warn before dispatch if party is overdue, blocked, near credit limit, or has risky payment behavior.",
    ai_opportunity:
      "Pre-empts risky dispatches before they leave the godown.",
    erp_modules: ["AI Layer", "Credit Control"],
    automation_potential: "high",
    position_x: COL(3),
    position_y: ROW_AI,
  },
  {
    node_key: "ai.goods_arrival_ocr",
    node_type: "ai",
    phase: "erp_ai",
    department: "ai_layer",
    visibility: "shared_all",
    title: "Goods Arrival OCR",
    description:
      "Read signed Goods Arrival Report and identify missing fields, quantity mismatch, damage/leakage, and oil loss.",
    ai_opportunity:
      "Speeds up condition-wise stock posting; catches damage/leakage claims earlier.",
    erp_modules: ["AI Layer", "Inventory"],
    automation_potential: "high",
    position_x: COL(1),
    position_y: ROW_AI,
  },
  {
    node_key: "ai.document_ocr",
    node_type: "ai",
    phase: "erp_ai",
    department: "ai_layer",
    visibility: "shared_all",
    title: "Document OCR & Checklist",
    description:
      "Verify invoice, Delivery Order, e-way bill, POD, and receiving copy.",
    ai_opportunity:
      "Removes the manual document recheck step before vehicle release.",
    erp_modules: ["AI Layer", "Documents"],
    automation_potential: "high",
    position_x: COL(5),
    position_y: ROW_AI,
  },
  {
    node_key: "ai.smart_stock_assistant",
    node_type: "ai",
    phase: "erp_ai",
    department: "ai_layer",
    visibility: "shared_all",
    title: "Smart Stock Assistant",
    description:
      "Answer stock questions by godown, batch, condition, in-transit status, reserved quantity, and saleable quantity.",
    ai_opportunity:
      "Conversational layer over inventory — sales team self-serves stock visibility.",
    erp_modules: ["AI Layer", "Inventory", "Decision Intelligence"],
    automation_potential: "high",
    position_x: COL(2),
    position_y: ROW_AI,
  },
  {
    node_key: "ai.margin_leakage",
    node_type: "ai",
    phase: "erp_ai",
    department: "ai_layer",
    visibility: "shared_all",
    title: "Margin Leakage Detection",
    description:
      "Detect low-margin or loss-making transactions after considering purchase rate, sales rate, discount, scheme, freight, oil loss, and damage.",
    ai_opportunity:
      "Quantifies the cost of operational shortfalls and ranks fixable transactions by margin impact.",
    erp_modules: ["AI Layer", "Decision Intelligence", "Sales"],
    automation_potential: "high",
    position_x: COL(6),
    position_y: ROW_AI,
  },
  {
    node_key: "ai.exception_dashboard",
    node_type: "ai",
    phase: "erp_ai",
    department: "ai_layer",
    visibility: "shared_all",
    title: "Exception Dashboard",
    description: "Highlight operational exceptions requiring management attention.",
    ai_opportunity:
      "Single pane for management — what to look at first, with explainability.",
    erp_modules: ["AI Layer", "Dashboard"],
    automation_potential: "high",
    position_x: COL(6),
    position_y: ROW_AI + 140,
  },
];

export const AI_EDGES: CanvasEdgeSeed[] = [
  // AI nodes attach to their corresponding ERP nodes
  ["ai.whatsapp_extraction", "erp.purchase.deal_booking"],
  ["ai.whatsapp_extraction", "erp.sales.deal_booking"],
  ["ai.whatsapp_extraction", "erp.purchase.approval_trail"],
  ["ai.whatsapp_extraction", "erp.dispatch.program"],
  ["ai.invoice_matching", "erp.purchase.invoice_import"],
  ["ai.invoice_matching", "erp.purchase.invoice_recon"],
  ["ai.credit_risk_alert", "erp.sales.credit_check"],
  ["ai.goods_arrival_ocr", "erp.inventory.goods_arrival"],
  ["ai.goods_arrival_ocr", "erp.inventory.condition_wise"],
  ["ai.document_ocr", "erp.billing.doc_checklist"],
  ["ai.document_ocr", "erp.billing.pod_upload"],
  ["ai.smart_stock_assistant", "erp.inventory.condition_wise"],
  ["ai.smart_stock_assistant", "erp.dashboard.management"],
  ["ai.margin_leakage", "erp.sales.deal_booking"],
  ["ai.margin_leakage", "erp.freight.management"],
  ["ai.margin_leakage", "erp.dashboard.management"],
  ["ai.exception_dashboard", "erp.dashboard.management"],
].map(([s, t], i) => ({
  edge_key: `ai.e${i + 1}`,
  source_node_key: s,
  target_node_key: t,
  edge_type: "ai_assisted",
  phase: "erp_ai" as const,
  visibility: "shared_all" as const,
}));

// =========================================================================
// COMBINED CANVAS — all nodes, all edges
// =========================================================================

export const SAURABH_NODES: CanvasNodeSeed[] = [
  ...CURRENT_NODES,
  ...ERP_NODES,
  ...AI_NODES,
];

export const SAURABH_EDGES: CanvasEdgeSeed[] = [
  ...CURRENT_EDGES,
  ...ERP_EDGES,
  ...AI_EDGES,
];

export const SAURABH_TEMPLATE = {
  slug: "refined_oil_cf",
  title: "Saurabh Arora — Workflow Canvas",
  subtitle: "Refined Oil Distribution / C&F Operations",
  canvas_type: "combined" as const,
  badges: ["Actual Client", "Partner Referral", "Discovery", "ERP + AI Workflow"],
  nodes: SAURABH_NODES,
  edges: SAURABH_EDGES,
};
